import type {
  CityHallProjectCategory,
  CityHallProjectDefinition,
} from "./cityHallTypes";

export const CITY_HALL_PROJECT_DURATION_TURNS = 3;

export const CITY_HALL_PROJECTS: CityHallProjectDefinition[] = [
  {
    id: "URBAN_REDEVELOPMENT_SUPPORT",
    name: "도시재개발 한시지원",
    category: "PROPERTY",
    summary: "소규모 건설 보조금을 한시적으로 집행합니다.",
    effectDescription: "전체 건설비 10% 감소",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { constructionCostMultiplier: 0.9 },
  },
  {
    id: "PROPERTY_STIMULUS",
    name: "지역 부동산 활력대책",
    category: "PROPERTY",
    summary: "단기 거래 촉진책으로 지역 부동산 흐름을 보완합니다.",
    effectDescription: "전체 부동산 시세 변동에 +2%p 보정",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { propertyMarketChangeBias: 0.02 },
  },
  {
    id: "HOUSING_MARKET_STABILIZATION",
    name: "주거시장 긴급안정",
    category: "PROPERTY",
    summary: "급격한 하락을 단기간 완충합니다.",
    effectDescription: "부동산 1회 하락 폭을 최대 -7%로 제한",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { propertyMarketMinimumChangeRate: -0.07 },
  },
  {
    id: "COMMERCIAL_DISTRICT_REVITALIZATION",
    name: "골목상권 활력주간",
    category: "PROPERTY",
    summary: "일반 상권의 유동인구와 단기 수익을 높입니다.",
    effectDescription: "비랜드마크 통행료 10% 증가",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { nonLandmarkTollMultiplier: 1.1 },
  },
  {
    id: "CORE_INDUSTRY_SUPPORT",
    name: "주력산업 단기지원",
    category: "STOCK",
    summary: "선정 산업에 소규모 정책 자금을 집행합니다.",
    effectDescription: "선정 주식 테마의 매 시장 변동에 +2%p",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "STOCK_INDUSTRY",
    effects: { stockIndustryChangeBias: 0.02 },
  },
  {
    id: "INVESTMENT_STABILIZATION_FUND",
    name: "투자시장 긴급안정",
    category: "STOCK",
    summary: "단기 급락 종목에 안정화 자금을 투입합니다.",
    effectDescription: "개별 종목의 1회 하락 폭을 최대 -12%로 제한",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { stockMinimumFinalChangeRate: -0.12 },
  },
  {
    id: "LOCAL_COMPANY_INVESTMENT_PROMOTION",
    name: "지역기업 투자촉진",
    category: "STOCK",
    summary: "선정 산업에 일회성 투자 촉진 자금을 공급합니다.",
    effectDescription: "다음 주식시장 정산에서 선정 테마에 +3%p",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "STOCK_INDUSTRY",
    effects: { oneTimeStockIndustryBoost: 0.03 },
  },
  {
    id: "LOCAL_TAX_REDUCTION",
    name: "한시 지방세 지원",
    category: "FINANCE",
    summary: "보유 부동산의 정기 세금 부담을 소폭 지원합니다.",
    effectDescription: "전체 부동산세 10% 감소",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { propertyTaxMultiplier: 0.9 },
  },
  {
    id: "SAVINGS_PROMOTION",
    name: "생활저축 장려기간",
    category: "FINANCE",
    summary: "일반예금 이자를 한시적으로 추가 지원합니다.",
    effectDescription: "일반예금 정기 이자 50% 증가",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { bankInterestMultiplier: 1.5 },
  },
  {
    id: "ULSAN_TOURISM_WEEK",
    name: "울산 관광주간",
    category: "PUBLIC",
    summary: "관광 수요를 단기간 집중시킵니다.",
    effectDescription: "랜드마크 통행료 15% 증가",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { landmarkTollMultiplier: 1.15 },
  },
  {
    id: "EXPORT_COMPANY_SUPPORT",
    name: "수출계약 행정지원",
    category: "PUBLIC",
    summary: "수출 계약의 행정·물류 지원을 한시적으로 강화합니다.",
    effectDescription: "울산항 계약 성공률 +8%p",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { portSuccessChanceDelta: 0.08 },
  },
  {
    id: "DISASTER_RECOVERY_SUPPORT",
    name: "재난복구 긴급지원",
    category: "PUBLIC",
    summary: "재난 피해 복구비 일부를 단기간 지원합니다.",
    effectDescription: "자연재해 최종 수리비 15% 감소",
    durationTurns: CITY_HALL_PROJECT_DURATION_TURNS,
    targetType: "NONE",
    effects: { disasterRepairCostMultiplier: 0.85 },
  },
];

export const CITY_HALL_PROJECT_CATEGORY_LABELS: Record<
  CityHallProjectCategory,
  string
> = {
  PROPERTY: "부동산·건설",
  STOCK: "산업·주식",
  FINANCE: "세금·금융",
  PUBLIC: "관광·안전·물류",
};
